{
  "openapi": "3.0.0",
  "info": {
    "title": "User Management Documentation",
    "description": "This is an API user management document",
    "version": "1.0.0",
    "contact": {
      "email": "seiti@mail.com"
    }
  },
  "paths":{
    "/users": {
      "post": {
        "tags": ["User"],
        "summary": "Create new user",
        "requestBody": {
          "content":{
            "application/json":{
              "schema":{
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "format": "uuid"
                  },
                  "name": {
                    "type": "string"
                  },
                  "email":{
                    "type": "string"
                  },
                  "admin":{
                    "type": "boolean"
                  },
                  "created_at": {
                    "type": "string"
                  },
                  "updated_at": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json":{
                "schema": {
                  "type": "array",
                  "items": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "format": "uuid"
                        },
                        "admin": {
                          "type": "boolean"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    
                  }
                },
                "examples": {
                  "UserExample": {
                    "value": [
                      {
                        "id": "3c9adaa9-8de4-47d1-8788-4f8b336f741c",
                        "admin": false,
                        "name": "Rocketseat",
                        "email": "oi@rocketseat.com.br",
                        "created_at": "2021-03-10T22:10:32.992Z",
                        "updated_at": "2021-03-10T22:10:32.992Z"
                      },
                      {
                        "id": "2e930901-cb97-403a-a7ac-c48d859ba188",
                        "admin": true,
                        "name": "Carlos",
                        "email": "carlos@rocketseat.com.br",
                        "created_at": "2021-03-22T15:10:32.992Z",
                        "updated_at": "2021-03-22T15:10:32.992Z"
                      }
                    ]    
                  }
              }
              }
            }
          },
          "400": {
            "description": "User already exists",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "You need to be an administrator to list all users."
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["User"],
        "summary": "List users",
        "description": "List users from a admin request",
        "parameters": [
            {
            "name": "user_id",
            "in": "header",
            "required": true,
            "schema":{
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200":{
            "description": "Success"
          },
          "400": {
            "description": "Non admin user",
            "content": {
              "application/json":  {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "User is not admin": {
                    "value": {
                      "error": "User is not admin"
                    }
                  },
                  "User does not exists": {
                    "value": {
                      "error": "User does not exists"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}":{
      "get": {
        "tags": ["User"],
        "summary": "Get specific user",
        "description": "Get specific user",
        "parameters": [
          {
            "in": "path",
            "name": "user_id",
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "required": true
          }
        ],
        "responses":{
          "200":{
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string",
                        "format": "uuid"
                      },
                      "admin": {
                        "type": "boolean"
                      },
                      "name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "updated_at": {
                        "type": "string"
                      }
                    }
                  }
                },
                "examples":{
                  "UserExample":{
                    "value": {
                      "id": "3c9adaa9-8de4-47d1-8788-4f8b336f741c",
                      "admin": false,
                      "name": "Rocketseat",
                      "email": "oi@rocketseat.com.br",
                      "created_at": "2021-03-10T22:10:32.992Z",
                      "updated_at": "2021-03-10T22:10:32.992Z"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "User does not exists"
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "tags": ["User"],
        "summary": "Set user as admin",
        "description": "Set user as admin",
        "parameters": [
          {
            "in": "path",
            "name": "user_id",
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/User"
                  }
                },
                "examples": {
                  "UserExample": {
                    "$ref": "#/components/examples/UserExample"
                  }
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "error": "User does not exists"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "admin": {
            "type": "boolean"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      }
    },
    "examples": {
      "UserExample": {
        "value": {
          "id": "3c9adaa9-8de4-47d1-8788-4f8b336f741c",
          "admin": false,
          "name": "Rocketseat",
          "email": "oi@rocketseat.com.br",
          "created_at": "2021-03-10T22:10:32.992Z",
          "updated_at": "2021-03-10T22:10:32.992Z"
        }
      },
      "UsersExample": {
        "value": [
          {
            "id": "3c9adaa9-8de4-47d1-8788-4f8b336f741c",
            "admin": false,
            "name": "Rocketseat",
            "email": "oi@rocketseat.com.br",
            "created_at": "2021-03-10T22:10:32.992Z",
            "updated_at": "2021-03-10T22:10:32.992Z"
          },
          {
            "id": "2e930901-cb97-403a-a7ac-c48d859ba188",
            "admin": true,
            "name": "Carlos",
            "email": "carlos@rocketseat.com.br",
            "created_at": "2021-03-22T15:10:32.992Z",
            "updated_at": "2021-03-22T15:10:32.992Z"
          }
        ]    
      }
    }
  }
}